package analysis;

import com.silita.biaodaa.analysisRules.notice.NoticeTableAnalysis;
import com.silita.biaodaa.service.ConfigTest;
import com.silita.biaodaa.utils.RegexUtils;
import org.junit.Test;
import org.springframework.beans.factory.annotation.Autowired;

import java.util.Arrays;

/**
 * Created by dh on 2018/10/31.
 */
public class TableAnalysisTest extends ConfigTest {

    @Autowired
    NoticeTableAnalysis noticeTableAnalysis;


    @Test
    public void testAnalysis()throws Exception{
        String s="   \n" +
                "  <table border=\"0\" align=\"left\" cellpadding=\"10\" cellspacing=\"0\"> \n" +
                "   <tbody> \n" +
                "    <tr> \n" +
                "     <td></td> \n" +
                "    </tr> \n" +
                "   </tbody> \n" +
                "  </table> \n" +
                "  <center>\n" +
                "    招标代码：04112018050062 \n" +
                "  </center> \n" +
                "  <epointform>\n" +
                "    &nbsp; \n" +
                "   <style>.A{font-family:宋体;font-size:12pt;color:#000000;background-color: #eaf3fb;border-left:#d1e6fa 1px solid;border-right:#d1e6fa 1px solid;border-top:#d1e6fa 1px solid;border-bottom:#d1e6fa 1px solid;}.B{font-family:宋体;font-size:12pt;color:#000000;background-color: #ffffff;border-left:#d1e6fa 1px solid;padding:10px;border-right:#d1e6fa 1px solid;border-top:#d1e6fa 1px solid;border-bottom:#d1e6fa 1px solid;}</style> \n" +
                "   <a class=\"ewebeditor__anchor\" name=\"Sheet1\" _ewebeditor_pa_name=\"Sheet1\"></a> \n" +
                "   <table style=\"BORDER-COLLAPSE: collapse; FONT-FAMILY: 宋体; TABLE-LAYOUT: fixed; COLOR: #000000; FONT-SIZE: 9pt\" id=\"_Sheet1\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"100%\" align=\"center\"> \n" +
                "    <tbody> \n" +
                "     <tr style=\"LINE-HEIGHT: 0px; FONT-SIZE: 0px\" height=\"0px\"> \n" +
                "      <td width=\"188\">&nbsp;</td> \n" +
                "      <td width=\"75\">&nbsp;</td> \n" +
                "      <td width=\"75\">&nbsp;</td> \n" +
                "      <td width=\"75\">&nbsp;</td> \n" +
                "      <td width=\"123\">&nbsp;</td> \n" +
                "      <td width=\"75\">&nbsp;</td> \n" +
                "      <td width=\"148\">&nbsp;</td> \n" +
                "     </tr> \n" +
                "     <tr> \n" +
                "      <td class=\"A\">标段编号</td> \n" +
                "      <td class=\"B\" colspan=\"3\">G21020120180129398211435694</td> \n" +
                "      <td class=\"A\">开标日期</td> \n" +
                "      <td class=\"B\" colspan=\"2\">2018年06月29日</td> \n" +
                "     </tr> \n" +
                "     <tr> \n" +
                "      <td class=\"A\">工程名称</td> \n" +
                "      <td class=\"B\" colspan=\"6\">马栏河运动公园一期建设工程亮化工程施工</td> \n" +
                "     </tr> \n" +
                "     <tr> \n" +
                "      <td class=\"A\">建设单位</td> \n" +
                "      <td class=\"B\" colspan=\"6\">大连市沙河口区城市建设管理局</td> \n" +
                "     </tr> \n" +
                "     <tr> \n" +
                "      <td class=\"A\">工程类别</td> \n" +
                "      <td class=\"B\" colspan=\"3\">施工类 </td> \n" +
                "      <td class=\"A\">招标方式</td> \n" +
                "      <td class=\"B\" colspan=\"2\">公开招标 </td> \n" +
                "     </tr> \n" +
                "     <tr height=\"30\"> \n" +
                "      <td class=\"A\">建设地点</td> \n" +
                "      <td class=\"B\" colspan=\"6\">大连市内</td> \n" +
                "     </tr> \n" +
                "     <tr> \n" +
                "      <td class=\"A\">中标范围和内容</td> \n" +
                "      <td class=\"B\" colspan=\"6\">包括灯具安装、线缆敷设等工程施工,具体详见施工图纸及工程量清单。</td> \n" +
                "     </tr> \n" +
                "     <tr> \n" +
                "      <td class=\"A\">代理机构</td> \n" +
                "      <td class=\"B\" colspan=\"6\">辽宁宏发工程管理咨询有限公司</td> \n" +
                "     </tr> \n" +
                "     <tr> \n" +
                "      <td class=\"A\">中标单位</td> \n" +
                "      <td class=\"B\" colspan=\"6\">大连路灯设计安装工程有限责任公司</td> \n" +
                "     </tr> \n" +
                "     <tr> \n" +
                "      <td class=\"A\">中标价</td> \n" +
                "      <td class=\"B\" colspan=\"3\"> <p><span style=\"BACKGROUND-COLOR: #ffffff; COLOR: #000000; FONT-SIZE: 12pt\">15458310.5300</span><span style=\"BACKGROUND-COLOR: #ffffff; COLOR: #000000; FONT-SIZE: 12pt\">元</span> &nbsp; </p></td> \n" +
                "      <td class=\"A\">建筑面积</td> \n" +
                "      <td class=\"B\" colspan=\"2\">&nbsp;平方米</td> \n" +
                "     </tr> \n" +
                "     <tr height=\"30\"> \n" +
                "      <td class=\"A\">中标单价（元/万平米）</td> \n" +
                "      <td class=\"B\" colspan=\"6\">0.00</td> \n" +
                "     </tr> \n" +
                "     <tr> \n" +
                "      <td class=\"A\">项目负责人姓名</td> \n" +
                "      <td class=\"B\" colspan=\"3\">迟建清</td> \n" +
                "      <td class=\"A\">项目负责人资格</td> \n" +
                "      <td class=\"B\" colspan=\"2\">机电工程&nbsp;&nbsp;一级注册建造师</td> \n" +
                "     </tr> \n" +
                "     <tr height=\"30\"> \n" +
                "      <td class=\"A\">项目负责人IC卡号</td> \n" +
                "      <td class=\"B\" colspan=\"3\">PNew2102000260</td> \n" +
                "      <td class=\"A\">有效工期（天）</td> \n" +
                "      <td class=\"B\" colspan=\"2\">60</td> \n" +
                "     </tr> \n" +
                "    </tbody> \n" +
                "   </table> \n" +
                "  </epointform>   \n" +
                " ";

       String s2="<tbody>\n" +
                " <tr> \n" +
                "  <td height=\"200\" valign=\"top\"> \n" +
                "   <table border=\"0\" align=\"left\" cellpadding=\"10\" cellspacing=\"0\"> \n" +
                "    <tbody>\n" +
                "     <tr> \n" +
                "      <td></td> \n" +
                "     </tr> \n" +
                "    </tbody>\n" +
                "   </table> \n" +
                "   <center>\n" +
                "    招标代码：00242018040406 建筑工程|\n" +
                "   </center><p style=\"TEXT-ALIGN: center; MARGIN: 0cm 0cm 0pt\" class=\"MsoNormal\" align=\"center\"><b style=\"mso-bidi-font-weight: normal\"><span style=\"FONT-FAMILY: 仿宋_GB2312; FONT-SIZE: 16pt; mso-hansi-font-family: 华文仿宋\">中标候选人公示<span lang=\"EN-US\">\n" +
                "       <!--?xml:namespace prefix = o ns = \"urn:schemas-microsoft-com:office:office\" /-->\n" +
                "       <o:p></o:p></span></span></b></p> <p style=\"TEXT-ALIGN: center; LINE-HEIGHT: 150%; MARGIN: 0cm 0cm 0pt; mso-pagination: widow-orphan\" class=\"MsoNormal\" align=\"center\"><span style=\"LINE-HEIGHT: 150%; FONT-FAMILY: 宋体; FONT-SIZE: 9pt; mso-hansi-font-family: &#x2ce;&#x325;; mso-font-kerning: 0pt; mso-ascii-font-family: &#x2ce;&#x325;; mso-bidi-font-family: 宋体\">项目编码：</span><font size=\"3\"><font face=\"Times New Roman\"><span style=\"LINE-HEIGHT: 150%; mso-bidi-font-size: 10.5pt\" lang=\"EN-US\">00242018040406</span><span style=\"LINE-HEIGHT: 150%; FONT-FAMILY: &#x2ce;&#x325;; COLOR: red; FONT-SIZE: 9pt; mso-font-kerning: 0pt; mso-bidi-font-family: 宋体\" lang=\"EN-US\">\n" +
                "       <o:p></o:p></span></font></font></p> <p style=\"TEXT-ALIGN: left; LINE-HEIGHT: 150%; TEXT-INDENT: 27pt; MARGIN: 0cm 0cm 0pt; LAYOUT-GRID-MODE: char; mso-pagination: widow-orphan; mso-char-indent-count: 2.0; mso-layout-grid-align: none\" class=\"MsoNormal\" align=\"left\"><span style=\"LINE-HEIGHT: 150%; FONT-FAMILY: 宋体; FONT-SIZE: 13.5pt; mso-hansi-font-family: &#x2ce;&#x325;; mso-font-kerning: 0pt; mso-ascii-font-family: &#x2ce;&#x325;; mso-bidi-font-family: 宋体\">辽中区大树林子险工治理工程评标工作于</span><span style=\"LINE-HEIGHT: 150%; FONT-FAMILY: &#x2ce;&#x325;; FONT-SIZE: 13.5pt; mso-font-kerning: 0pt; mso-bidi-font-family: 宋体\" lang=\"EN-US\"><font face=\"Times New Roman\">2018</font></span><span style=\"LINE-HEIGHT: 150%; FONT-FAMILY: 宋体; FONT-SIZE: 13.5pt; mso-hansi-font-family: &#x2ce;&#x325;; mso-font-kerning: 0pt; mso-ascii-font-family: &#x2ce;&#x325;; mso-bidi-font-family: 宋体\">年</span><span style=\"LINE-HEIGHT: 150%; FONT-FAMILY: &#x2ce;&#x325;; FONT-SIZE: 13.5pt; mso-font-kerning: 0pt; mso-bidi-font-family: 宋体\" lang=\"EN-US\"><font face=\"Times New Roman\">4</font></span><span style=\"LINE-HEIGHT: 150%; FONT-FAMILY: 宋体; FONT-SIZE: 13.5pt; mso-hansi-font-family: &#x2ce;&#x325;; mso-font-kerning: 0pt; mso-ascii-font-family: &#x2ce;&#x325;; mso-bidi-font-family: 宋体\">月</span><span style=\"LINE-HEIGHT: 150%; FONT-FAMILY: &#x2ce;&#x325;; FONT-SIZE: 13.5pt; mso-font-kerning: 0pt; mso-bidi-font-family: 宋体\" lang=\"EN-US\"><font face=\"Times New Roman\">25</font></span><span style=\"LINE-HEIGHT: 150%; FONT-FAMILY: 宋体; FONT-SIZE: 13.5pt; mso-hansi-font-family: &#x2ce;&#x325;; mso-font-kerning: 0pt; mso-ascii-font-family: &#x2ce;&#x325;; mso-bidi-font-family: 宋体\">日在沈阳公共资源交易中心</span><span style=\"LINE-HEIGHT: 150%; FONT-FAMILY: &#x2ce;&#x325;; FONT-SIZE: 13.5pt; mso-font-kerning: 0pt; mso-bidi-font-family: 宋体\" lang=\"EN-US\"><font face=\"Times New Roman\">B</font></span><span style=\"LINE-HEIGHT: 150%; FONT-FAMILY: 宋体; FONT-SIZE: 13.5pt; mso-hansi-font-family: &#x2ce;&#x325;; mso-font-kerning: 0pt; mso-ascii-font-family: &#x2ce;&#x325;; mso-bidi-font-family: 宋体\">座十七楼第十八评标室结束，现将评标委员会推荐的中标候选人名单公示如下，公示期为三日，如有疑义，请在公示期内以真实姓名和单位向该项目的监管部门反映。</span><span style=\"LINE-HEIGHT: 150%; FONT-FAMILY: &#x2ce;&#x325;; FONT-SIZE: 13.5pt; mso-font-kerning: 0pt; mso-bidi-font-family: 宋体\"><font face=\"Times New Roman\"> <span style=\"mso-spacerun: yes\">&nbsp;</span><span lang=\"EN-US\">\n" +
                "       <o:p></o:p></span></font></span></p> \n" +
                "   <div align=\"center\"> \n" +
                "    <table style=\"BORDER-BOTTOM: medium none; BORDER-LEFT: medium none; BORDER-COLLAPSE: collapse; BORDER-TOP: medium none; BORDER-RIGHT: medium none; mso-table-layout-alt: fixed; mso-border-alt: solid windowtext .5pt; mso-padding-alt: 0cm 5.4pt 0cm 5.4pt; mso-border-insideh: .5pt solid windowtext; mso-border-insidev: .5pt solid windowtext\" class=\"MsoNormalTable\" border=\"1\" cellspacing=\"0\" cellpadding=\"0\"> \n" +
                "     <tbody> \n" +
                "      <tr style=\"HEIGHT: 36.1pt; mso-yfti-irow: 0; mso-yfti-firstrow: yes\"> \n" +
                "       <td style=\"BORDER-BOTTOM: windowtext 1pt solid; BORDER-LEFT: windowtext 1pt solid; PADDING-BOTTOM: 0cm; BACKGROUND-COLOR: transparent; PADDING-LEFT: 5.4pt; WIDTH: 113.75pt; PADDING-RIGHT: 5.4pt; HEIGHT: 36.1pt; BORDER-TOP: windowtext 1pt solid; BORDER-RIGHT: windowtext 1pt solid; PADDING-TOP: 0cm; mso-border-alt: solid windowtext .5pt\" width=\"152\"> <p style=\"TEXT-ALIGN: center; MARGIN: 0cm 0cm 0pt; LAYOUT-GRID-MODE: char; mso-pagination: widow-orphan\" class=\"MsoNormal\" align=\"center\"><span style=\"FONT-FAMILY: 宋体; FONT-SIZE: 12pt; mso-font-kerning: 0pt; mso-bidi-font-family: 宋体\">项目名称<span lang=\"EN-US\">\n" +
                "           <o:p></o:p></span></span></p></td> \n" +
                "       <td style=\"BORDER-BOTTOM: windowtext 1pt solid; BORDER-LEFT: #dce0e7; PADDING-BOTTOM: 0cm; BACKGROUND-COLOR: transparent; PADDING-LEFT: 5.4pt; WIDTH: 399.95pt; PADDING-RIGHT: 5.4pt; HEIGHT: 36.1pt; BORDER-TOP: windowtext 1pt solid; BORDER-RIGHT: windowtext 1pt solid; PADDING-TOP: 0cm; mso-border-alt: solid windowtext .5pt; mso-border-left-alt: solid windowtext .5pt\" width=\"533\" colspan=\"3\"> <p style=\"TEXT-ALIGN: center; MARGIN: 0cm 0cm 0pt; LAYOUT-GRID-MODE: char; mso-pagination: widow-orphan; mso-layout-grid-align: none\" class=\"MsoNormal\" align=\"center\"><span style=\"FONT-FAMILY: 宋体; FONT-SIZE: 12pt; mso-font-kerning: 0pt; mso-bidi-font-family: 宋体\">辽中区大树林子险工治理工程<span lang=\"EN-US\">\n" +
                "           <o:p></o:p></span></span></p></td>\n" +
                "      </tr> \n" +
                "      <tr style=\"HEIGHT: 33.05pt; mso-yfti-irow: 1\"> \n" +
                "       <td style=\"BORDER-BOTTOM: windowtext 1pt solid; BORDER-LEFT: windowtext 1pt solid; PADDING-BOTTOM: 0cm; BACKGROUND-COLOR: transparent; PADDING-LEFT: 5.4pt; WIDTH: 113.75pt; PADDING-RIGHT: 5.4pt; HEIGHT: 33.05pt; BORDER-TOP: #dce0e7; BORDER-RIGHT: windowtext 1pt solid; PADDING-TOP: 0cm; mso-border-alt: solid windowtext .5pt; mso-border-top-alt: solid windowtext .5pt\" width=\"152\"> <p style=\"TEXT-ALIGN: center; MARGIN: 0cm 0cm 0pt; LAYOUT-GRID-MODE: char; mso-pagination: widow-orphan\" class=\"MsoNormal\" align=\"center\"><span style=\"FONT-FAMILY: 宋体; FONT-SIZE: 12pt; mso-font-kerning: 0pt; mso-bidi-font-family: 宋体\">投标人排序<span lang=\"EN-US\">\n" +
                "           <o:p></o:p></span></span></p></td> \n" +
                "       <td style=\"BORDER-BOTTOM: windowtext 1pt solid; BORDER-LEFT: #dce0e7; PADDING-BOTTOM: 0cm; BACKGROUND-COLOR: transparent; PADDING-LEFT: 5.4pt; WIDTH: 129pt; PADDING-RIGHT: 5.4pt; HEIGHT: 33.05pt; BORDER-TOP: #dce0e7; BORDER-RIGHT: windowtext 1pt solid; PADDING-TOP: 0cm; mso-border-alt: solid windowtext .5pt; mso-border-left-alt: solid windowtext .5pt; mso-border-top-alt: solid windowtext .5pt\" width=\"172\"> <p style=\"TEXT-ALIGN: center; MARGIN: 0cm 0cm 0pt; LAYOUT-GRID-MODE: char; mso-pagination: widow-orphan; mso-layout-grid-align: none\" class=\"MsoNormal\" align=\"center\"><span style=\"FONT-FAMILY: 宋体; FONT-SIZE: 12pt; mso-font-kerning: 0pt; mso-bidi-font-family: 宋体\">第一名<span lang=\"EN-US\">\n" +
                "           <o:p></o:p></span></span></p></td> \n" +
                "       <td style=\"BORDER-BOTTOM: windowtext 1pt solid; BORDER-LEFT: #dce0e7; PADDING-BOTTOM: 0cm; BACKGROUND-COLOR: transparent; PADDING-LEFT: 5.4pt; WIDTH: 137.75pt; PADDING-RIGHT: 5.4pt; HEIGHT: 33.05pt; BORDER-TOP: #dce0e7; BORDER-RIGHT: windowtext 1pt solid; PADDING-TOP: 0cm; mso-border-alt: solid windowtext .5pt; mso-border-left-alt: solid windowtext .5pt; mso-border-top-alt: solid windowtext .5pt\" width=\"184\"> <p style=\"TEXT-ALIGN: center; MARGIN: 0cm 0cm 0pt; LAYOUT-GRID-MODE: char; mso-pagination: widow-orphan; mso-layout-grid-align: none\" class=\"MsoNormal\" align=\"center\"><span style=\"FONT-FAMILY: 宋体; FONT-SIZE: 12pt; mso-font-kerning: 0pt; mso-bidi-font-family: 宋体\">第二名<span lang=\"EN-US\">\n" +
                "           <o:p></o:p></span></span></p></td> \n" +
                "       <td style=\"BORDER-BOTTOM: windowtext 1pt solid; BORDER-LEFT: #dce0e7; PADDING-BOTTOM: 0cm; BACKGROUND-COLOR: transparent; PADDING-LEFT: 5.4pt; WIDTH: 133.2pt; PADDING-RIGHT: 5.4pt; HEIGHT: 33.05pt; BORDER-TOP: #dce0e7; BORDER-RIGHT: windowtext 1pt solid; PADDING-TOP: 0cm; mso-border-alt: solid windowtext .5pt; mso-border-left-alt: solid windowtext .5pt; mso-border-top-alt: solid windowtext .5pt\" width=\"178\"> <p style=\"TEXT-ALIGN: center; MARGIN: 0cm 0cm 0pt; LAYOUT-GRID-MODE: char; mso-pagination: widow-orphan; mso-layout-grid-align: none\" class=\"MsoNormal\" align=\"center\"><span style=\"FONT-FAMILY: 宋体; FONT-SIZE: 12pt; mso-font-kerning: 0pt; mso-bidi-font-family: 宋体\">第三名<span lang=\"EN-US\">\n" +
                "           <o:p></o:p></span></span></p></td>\n" +
                "      </tr> \n" +
                "      <tr style=\"HEIGHT: 54.7pt; mso-yfti-irow: 2; mso-yfti-lastrow: yes\"> \n" +
                "       <td style=\"BORDER-BOTTOM: windowtext 1pt solid; BORDER-LEFT: windowtext 1pt solid; PADDING-BOTTOM: 0cm; BACKGROUND-COLOR: transparent; PADDING-LEFT: 5.4pt; WIDTH: 113.75pt; PADDING-RIGHT: 5.4pt; HEIGHT: 54.7pt; BORDER-TOP: #dce0e7; BORDER-RIGHT: windowtext 1pt solid; PADDING-TOP: 0cm; mso-border-alt: solid windowtext .5pt; mso-border-top-alt: solid windowtext .5pt\" width=\"152\"> <p style=\"TEXT-ALIGN: center; MARGIN: 0cm 0cm 0pt; LAYOUT-GRID-MODE: char; mso-pagination: widow-orphan\" class=\"MsoNormal\" align=\"center\"><span style=\"FONT-FAMILY: 宋体; FONT-SIZE: 12pt; mso-font-kerning: 0pt; mso-bidi-font-family: 宋体\">中标候选人名称<span lang=\"EN-US\">\n" +
                "           <o:p></o:p></span></span></p></td> \n" +
                "       <td style=\"BORDER-BOTTOM: windowtext 1pt solid; BORDER-LEFT: #dce0e7; PADDING-BOTTOM: 0cm; BACKGROUND-COLOR: transparent; PADDING-LEFT: 5.4pt; WIDTH: 129pt; PADDING-RIGHT: 5.4pt; HEIGHT: 54.7pt; BORDER-TOP: #dce0e7; BORDER-RIGHT: windowtext 1pt solid; PADDING-TOP: 0cm; mso-border-alt: solid windowtext .5pt; mso-border-left-alt: solid windowtext .5pt; mso-border-top-alt: solid windowtext .5pt\" width=\"172\"> <p style=\"TEXT-ALIGN: center; MARGIN: 0cm 0cm 0pt; LAYOUT-GRID-MODE: char; mso-pagination: widow-orphan; mso-layout-grid-align: none\" class=\"MsoNormal\" align=\"center\"><span style=\"FONT-FAMILY: 宋体; FONT-SIZE: 12pt; mso-font-kerning: 0pt; mso-bidi-font-family: 宋体\">沈阳威远建筑工程有限责任公司<span lang=\"EN-US\">\n" +
                "           <o:p></o:p></span></span></p></td> \n" +
                "       <td style=\"BORDER-BOTTOM: windowtext 1pt solid; BORDER-LEFT: #dce0e7; PADDING-BOTTOM: 0cm; BACKGROUND-COLOR: transparent; PADDING-LEFT: 5.4pt; WIDTH: 137.75pt; PADDING-RIGHT: 5.4pt; HEIGHT: 54.7pt; BORDER-TOP: #dce0e7; BORDER-RIGHT: windowtext 1pt solid; PADDING-TOP: 0cm; mso-border-alt: solid windowtext .5pt; mso-border-left-alt: solid windowtext .5pt; mso-border-top-alt: solid windowtext .5pt\" width=\"184\"> <p style=\"TEXT-ALIGN: center; MARGIN: 0cm 0cm 0pt; LAYOUT-GRID-MODE: char; mso-pagination: widow-orphan; mso-layout-grid-align: none\" class=\"MsoNormal\" align=\"center\"><span style=\"FONT-FAMILY: 宋体; FONT-SIZE: 12pt; mso-font-kerning: 0pt; mso-bidi-font-family: 宋体\">沈阳市辽中区水利建筑工程公司<span lang=\"EN-US\">\n" +
                "           <o:p></o:p></span></span></p></td> \n" +
                "       <td style=\"BORDER-BOTTOM: windowtext 1pt solid; BORDER-LEFT: #dce0e7; PADDING-BOTTOM: 0cm; BACKGROUND-COLOR: transparent; PADDING-LEFT: 5.4pt; WIDTH: 133.2pt; PADDING-RIGHT: 5.4pt; HEIGHT: 54.7pt; BORDER-TOP: #dce0e7; BORDER-RIGHT: windowtext 1pt solid; PADDING-TOP: 0cm; mso-border-alt: solid windowtext .5pt; mso-border-left-alt: solid windowtext .5pt; mso-border-top-alt: solid windowtext .5pt\" width=\"178\"> <p style=\"TEXT-ALIGN: center; MARGIN: 0cm 0cm 0pt; LAYOUT-GRID-MODE: char; mso-pagination: widow-orphan; mso-layout-grid-align: none\" class=\"MsoNormal\" align=\"center\"><span style=\"FONT-FAMILY: 宋体; FONT-SIZE: 12pt; mso-font-kerning: 0pt; mso-bidi-font-family: 宋体\">辽宁恒建土木工程有限公司<span lang=\"EN-US\">\n" +
                "           <o:p></o:p></span></span></p></td>\n" +
                "      </tr>\n" +
                "     </tbody>\n" +
                "    </table>\n" +
                "   </div> <p style=\"TEXT-ALIGN: left; LINE-HEIGHT: 20pt; MARGIN: 0cm 0cm 0pt; LAYOUT-GRID-MODE: char; mso-pagination: widow-orphan; mso-layout-grid-align: none; mso-line-height-rule: exactly\" class=\"MsoNormal\" align=\"left\"><span style=\"FONT-FAMILY: &#x2ce;&#x325;; FONT-SIZE: 13.5pt; mso-font-kerning: 0pt; mso-bidi-font-family: 宋体\" lang=\"EN-US\">\n" +
                "     <o:p>\n" +
                "      <font face=\"Times New Roman\">&nbsp;</font>\n" +
                "     </o:p></span></p> <p style=\"TEXT-ALIGN: left; LINE-HEIGHT: 20pt; MARGIN: 0cm 0cm 0pt; LAYOUT-GRID-MODE: char; mso-pagination: widow-orphan; mso-layout-grid-align: none; mso-line-height-rule: exactly\" class=\"MsoNormal\" align=\"left\"><span style=\"FONT-FAMILY: 宋体; FONT-SIZE: 13.5pt; mso-hansi-font-family: &#x2ce;&#x325;; mso-font-kerning: 0pt; mso-ascii-font-family: &#x2ce;&#x325;; mso-bidi-font-family: 宋体\">招标人：沈阳市辽中区辽河综合建设工程管理处</span><span style=\"FONT-FAMILY: &#x2ce;&#x325;; FONT-SIZE: 13.5pt; mso-font-kerning: 0pt; mso-bidi-font-family: 宋体\" lang=\"EN-US\">\n" +
                "     <o:p></o:p></span></p> <p style=\"TEXT-ALIGN: left; LINE-HEIGHT: 20pt; MARGIN: 0cm 0cm 0pt; LAYOUT-GRID-MODE: char; mso-pagination: widow-orphan; mso-layout-grid-align: none; mso-line-height-rule: exactly\" class=\"MsoNormal\" align=\"left\"><span style=\"FONT-FAMILY: 宋体; FONT-SIZE: 13.5pt; mso-hansi-font-family: &#x2ce;&#x325;; mso-font-kerning: 0pt; mso-ascii-font-family: &#x2ce;&#x325;; mso-bidi-font-family: 宋体\">办公地址：沈阳市辽中区</span><span style=\"FONT-FAMILY: &#x2ce;&#x325;; FONT-SIZE: 13.5pt; mso-font-kerning: 0pt; mso-bidi-font-family: 宋体\" lang=\"EN-US\">\n" +
                "     <o:p></o:p></span></p> <p style=\"TEXT-ALIGN: left; LINE-HEIGHT: 20pt; MARGIN: 0cm 0cm 0pt; LAYOUT-GRID-MODE: char; mso-pagination: widow-orphan; mso-layout-grid-align: none; mso-line-height-rule: exactly\" class=\"MsoNormal\" align=\"left\"><span style=\"FONT-FAMILY: 宋体; FONT-SIZE: 13.5pt; mso-hansi-font-family: &#x2ce;&#x325;; mso-font-kerning: 0pt; mso-ascii-font-family: &#x2ce;&#x325;; mso-bidi-font-family: 宋体\">招标代理人：辽宁东奥招标投标咨询有限公司</span><span style=\"FONT-FAMILY: &#x2ce;&#x325;; FONT-SIZE: 13.5pt; mso-font-kerning: 0pt; mso-bidi-font-family: 宋体\" lang=\"EN-US\">\n" +
                "     <o:p></o:p></span></p> <p style=\"TEXT-ALIGN: left; LINE-HEIGHT: 20pt; MARGIN: 0cm 0cm 0pt; LAYOUT-GRID-MODE: char; mso-pagination: widow-orphan; mso-layout-grid-align: none; mso-line-height-rule: exactly\" class=\"MsoNormal\" align=\"left\"><span style=\"FONT-FAMILY: 宋体; FONT-SIZE: 13.5pt; mso-hansi-font-family: &#x2ce;&#x325;; mso-font-kerning: 0pt; mso-ascii-font-family: &#x2ce;&#x325;; mso-bidi-font-family: 宋体\">办公地址：浑南新区新隆街</span><span style=\"FONT-FAMILY: &#x2ce;&#x325;; FONT-SIZE: 13.5pt; mso-font-kerning: 0pt; mso-bidi-font-family: 宋体\" lang=\"EN-US\"><font face=\"Times New Roman\">1</font></span><span style=\"FONT-FAMILY: 宋体; FONT-SIZE: 13.5pt; mso-hansi-font-family: &#x2ce;&#x325;; mso-font-kerning: 0pt; mso-ascii-font-family: &#x2ce;&#x325;; mso-bidi-font-family: 宋体\">号万科明天广场</span><span style=\"FONT-FAMILY: &#x2ce;&#x325;; FONT-SIZE: 13.5pt; mso-font-kerning: 0pt; mso-bidi-font-family: 宋体\" lang=\"EN-US\"><font face=\"Times New Roman\">D</font></span><span style=\"FONT-FAMILY: 宋体; FONT-SIZE: 13.5pt; mso-hansi-font-family: &#x2ce;&#x325;; mso-font-kerning: 0pt; mso-ascii-font-family: &#x2ce;&#x325;; mso-bidi-font-family: 宋体\">座</span><span style=\"FONT-FAMILY: &#x2ce;&#x325;; FONT-SIZE: 13.5pt; mso-font-kerning: 0pt; mso-bidi-font-family: 宋体\" lang=\"EN-US\"><font face=\"Times New Roman\">505\n" +
                "      <o:p></o:p></font></span></p> <p style=\"TEXT-ALIGN: left; LINE-HEIGHT: 20pt; MARGIN: 0cm 0cm 0pt; LAYOUT-GRID-MODE: char; mso-pagination: widow-orphan; mso-layout-grid-align: none; mso-line-height-rule: exactly\" class=\"MsoNormal\" align=\"left\"><span style=\"FONT-FAMILY: 宋体; FONT-SIZE: 13.5pt; mso-hansi-font-family: &#x2ce;&#x325;; mso-font-kerning: 0pt; mso-ascii-font-family: &#x2ce;&#x325;; mso-bidi-font-family: 宋体\">联系人：陈文哲</span><span style=\"FONT-FAMILY: &#x2ce;&#x325;; FONT-SIZE: 13.5pt; mso-font-kerning: 0pt; mso-bidi-font-family: 宋体\" lang=\"EN-US\">\n" +
                "     <o:p></o:p></span></p> <p style=\"TEXT-ALIGN: left; LINE-HEIGHT: 20pt; MARGIN: 0cm 0cm 0pt; LAYOUT-GRID-MODE: char; mso-pagination: widow-orphan; mso-layout-grid-align: none; mso-line-height-rule: exactly\" class=\"MsoNormal\" align=\"left\"><span style=\"FONT-FAMILY: 宋体; FONT-SIZE: 13.5pt; mso-hansi-font-family: &#x2ce;&#x325;; mso-font-kerning: 0pt; mso-ascii-font-family: &#x2ce;&#x325;; mso-bidi-font-family: 宋体\">联系电话：</span><span style=\"FONT-FAMILY: &#x2ce;&#x325;; FONT-SIZE: 13.5pt; mso-font-kerning: 0pt; mso-bidi-font-family: 宋体\" lang=\"EN-US\"><font face=\"Times New Roman\">024-31092775\n" +
                "      <o:p></o:p></font></span></p> <p style=\"TEXT-ALIGN: left; LINE-HEIGHT: 20pt; MARGIN: 0cm 0cm 0pt; LAYOUT-GRID-MODE: char; mso-pagination: widow-orphan; mso-layout-grid-align: none; mso-line-height-rule: exactly\" class=\"MsoNormal\" align=\"left\"><span style=\"FONT-FAMILY: 宋体; FONT-SIZE: 13.5pt; mso-hansi-font-family: &#x2ce;&#x325;; mso-font-kerning: 0pt; mso-ascii-font-family: &#x2ce;&#x325;; mso-bidi-font-family: 宋体\">传真：</span><span style=\"FONT-FAMILY: &#x2ce;&#x325;; FONT-SIZE: 13.5pt; mso-font-kerning: 0pt; mso-bidi-font-family: 宋体\" lang=\"EN-US\"><font face=\"Times New Roman\">024-31092775\n" +
                "      <o:p></o:p></font></span></p> <p style=\"TEXT-ALIGN: left; LINE-HEIGHT: 20pt; MARGIN: 0cm 0cm 0pt; LAYOUT-GRID-MODE: char; mso-pagination: widow-orphan; mso-layout-grid-align: none; mso-line-height-rule: exactly\" class=\"MsoNormal\" align=\"left\"><span style=\"FONT-FAMILY: 宋体; FONT-SIZE: 13.5pt; mso-hansi-font-family: &#x2ce;&#x325;; mso-font-kerning: 0pt; mso-ascii-font-family: &#x2ce;&#x325;; mso-bidi-font-family: 宋体\">邮编：</span><span style=\"FONT-FAMILY: &#x2ce;&#x325;; FONT-SIZE: 13.5pt; mso-font-kerning: 0pt; mso-bidi-font-family: 宋体\" lang=\"EN-US\"><font face=\"Times New Roman\">110000\n" +
                "      <o:p></o:p></font></span></p> <p style=\"TEXT-ALIGN: right; LINE-HEIGHT: 150%; MARGIN: 0cm 27pt 0pt 0cm; LAYOUT-GRID-MODE: char; mso-pagination: widow-orphan; mso-layout-grid-align: none\" class=\"MsoNormal\" align=\"right\"><span style=\"LINE-HEIGHT: 150%; FONT-FAMILY: &#x2ce;&#x325;; FONT-SIZE: 9pt; mso-font-kerning: 0pt; mso-bidi-font-family: 宋体\" lang=\"EN-US\">\n" +
                "     <o:p>\n" +
                "      <font face=\"Times New Roman\">&nbsp;</font>\n" +
                "     </o:p></span></p><font face=\"宋体\"><span style=\"FONT-FAMILY: &#x2ce;&#x325;; FONT-SIZE: 13.5pt; mso-fareast-font-family: 宋体; mso-bidi-font-family: 宋体; mso-ansi-language: EN-US; mso-fareast-language: ZH-CN; mso-bidi-language: AR-SA\" lang=\"EN-US\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2018</span><span style=\"FONT-FAMILY: 宋体; FONT-SIZE: 13.5pt; mso-hansi-font-family: &#x2ce;&#x325;; mso-ascii-font-family: &#x2ce;&#x325;; mso-bidi-font-family: 宋体; mso-ansi-language: EN-US; mso-fareast-language: ZH-CN; mso-bidi-language: AR-SA\">年</span><span style=\"FONT-FAMILY: &#x2ce;&#x325;; FONT-SIZE: 13.5pt; mso-fareast-font-family: 宋体; mso-bidi-font-family: 宋体; mso-ansi-language: EN-US; mso-fareast-language: ZH-CN; mso-bidi-language: AR-SA\" lang=\"EN-US\">4</span><span style=\"FONT-FAMILY: 宋体; FONT-SIZE: 13.5pt; mso-hansi-font-family: &#x2ce;&#x325;; mso-ascii-font-family: &#x2ce;&#x325;; mso-bidi-font-family: 宋体; mso-ansi-language: EN-US; mso-fareast-language: ZH-CN; mso-bidi-language: AR-SA\">月</span><span style=\"FONT-FAMILY: &#x2ce;&#x325;; FONT-SIZE: 13.5pt; mso-fareast-font-family: 宋体; mso-bidi-font-family: 宋体; mso-ansi-language: EN-US; mso-fareast-language: ZH-CN; mso-bidi-language: AR-SA\" lang=\"EN-US\">26</span><span style=\"FONT-FAMILY: 宋体; FONT-SIZE: 13.5pt; mso-hansi-font-family: &#x2ce;&#x325;; mso-ascii-font-family: &#x2ce;&#x325;; mso-bidi-font-family: 宋体; mso-ansi-language: EN-US; mso-fareast-language: ZH-CN; mso-bidi-language: AR-SA\">日</span></font> </td> \n" +
                " </tr> \n" +
                "</tbody>";

        String s3="<td height=\"200\" valign=\"top\"> <table border=\"0\" align=\"left\" cellpadding=\"10\" cellspacing=\"0\">\n" +
                "                    <tbody><tr>\n" +
                "                      <td></td>\n" +
                "                    </tr>\n" +
                "                  </tbody></table>\n" +
                "                  <center>招标代码：00242018010088 </center><p style=\"TEXT-ALIGN: center; TEXT-INDENT: 18pt; MARGIN: 0cm 0cm 0pt; BACKGROUND: #fbfdff; mso-char-indent-count: 1.0; mso-pagination: widow-orphan\" class=\"MsoNormal\" align=\"center\"><b><u><span style=\"FONT-FAMILY: '微软雅黑','sans-serif'; COLOR: #333333; FONT-SIZE: 18pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\">（锦承线数字移动通信系统（<span lang=\"EN-US\">GSM-R</span>）改造工程<span lang=\"EN-US\"><!--?xml:namespace prefix = o ns = \"urn:schemas-microsoft-com:office:office\" /--><o:p></o:p></span></span></u></b></p>\n" +
                "<p style=\"TEXT-ALIGN: center; TEXT-INDENT: 18pt; MARGIN: 0cm 0cm 0pt; BACKGROUND: #fbfdff; mso-char-indent-count: 1.0; mso-pagination: widow-orphan\" class=\"MsoNormal\" align=\"center\"><b><u><span style=\"FONT-FAMILY: '微软雅黑','sans-serif'; COLOR: #333333; FONT-SIZE: 18pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\">勘察设计）</span></u></b><b><span style=\"FONT-FAMILY: '微软雅黑','sans-serif'; COLOR: #333333; FONT-SIZE: 18pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\">中标候选人公示<span lang=\"EN-US\"><o:p></o:p></span></span></b></p>\n" +
                "<p style=\"TEXT-ALIGN: center; TEXT-INDENT: 18pt; MARGIN: 0cm 0cm 0pt; BACKGROUND: #fbfdff; mso-char-indent-count: 1.0; mso-pagination: widow-orphan\" class=\"MsoNormal\" align=\"center\"><b><span style=\"FONT-FAMILY: '微软雅黑','sans-serif'; COLOR: #333333; FONT-SIZE: 18pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\" lang=\"EN-US\"><o:p>&nbsp;</o:p></span></b></p>\n" +
                "<p style=\"TEXT-ALIGN: left; TEXT-INDENT: 138pt; MARGIN: 0cm 0cm 0pt; BACKGROUND: #fbfdff; mso-char-indent-count: 11.5; mso-pagination: widow-orphan\" class=\"MsoNormal\" align=\"left\"><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\">招标编号：<span lang=\"EN-US\">STLXJSF2018-001<o:p></o:p></span></span></p>\n" +
                "<p style=\"TEXT-ALIGN: center; TEXT-INDENT: 18pt; MARGIN: 0cm 0cm 0pt; BACKGROUND: #fbfdff; mso-char-indent-count: 1.0; mso-pagination: widow-orphan\" class=\"MsoNormal\" align=\"center\"><b><span style=\"FONT-FAMILY: '微软雅黑','sans-serif'; COLOR: #333333; FONT-SIZE: 18pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\" lang=\"EN-US\"><o:p>&nbsp;</o:p></span></b></p>\n" +
                "<p style=\"TEXT-ALIGN: left; MARGIN: 0cm 0cm 0pt; mso-pagination: widow-orphan\" class=\"MsoNormal\" align=\"left\"><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\" lang=\"EN-US\">&nbsp; </span><u><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\">（锦承线数字移动通信系统（<span lang=\"EN-US\">GSM-R</span>）改造工程勘察设计）</span></u><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\">的招标评标工作已经结束，评标委员会经评审推荐了本项目中标候选人。现就本次招标的中标候选人公示如下：<span lang=\"EN-US\"><o:p></o:p></span></span></p>\n" +
                "<p style=\"TEXT-ALIGN: left; TEXT-INDENT: 28.45pt; MARGIN: 0cm 0cm 0pt; mso-char-indent-count: 2.36; mso-pagination: widow-orphan\" class=\"MsoNormal\" align=\"left\"><b style=\"mso-bidi-font-weight: normal\"><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\">一、中标候选人：<span lang=\"EN-US\"><o:p></o:p></span></span></b></p>\n" +
                "<p style=\"TEXT-ALIGN: left; TEXT-INDENT: 28.45pt; MARGIN: 0cm 0cm 0pt; mso-char-indent-count: 2.36; mso-pagination: widow-orphan\" class=\"MsoNormal\" align=\"left\"><b style=\"mso-bidi-font-weight: normal\"><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\" lang=\"EN-US\"><o:p>&nbsp;</o:p></span></b></p>\n" +
                "<p style=\"TEXT-ALIGN: left; TEXT-INDENT: 28.3pt; MARGIN: 0cm 0cm 0pt; mso-char-indent-count: 2.36; mso-pagination: widow-orphan\" class=\"MsoNormal\" align=\"left\"><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\" lang=\"EN-US\">1</span><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\">、（标段号<span lang=\"EN-US\">/</span>包件号）<span lang=\"EN-US\">:(</span>标段<span lang=\"EN-US\">/</span>包件名称：勘察设计<span lang=\"EN-US\">)<o:p></o:p></span></span></p>\n" +
                "<p style=\"TEXT-ALIGN: left; TEXT-INDENT: 28.3pt; MARGIN: 0cm 0cm 0pt; mso-char-indent-count: 2.36; mso-pagination: widow-orphan\" class=\"MsoNormal\" align=\"left\"><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\" lang=\"EN-US\"><o:p>&nbsp;</o:p></span></p>\n" +
                "<p style=\"TEXT-ALIGN: left; MARGIN: 0cm 0cm 0pt; mso-pagination: widow-orphan\" class=\"MsoNormal\" align=\"left\"><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\" lang=\"EN-US\"><span style=\"mso-spacerun: yes\">&nbsp;&nbsp; </span></span><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\">第一名：经评审的投标报价<span lang=\"EN-US\">(</span>元<span lang=\"EN-US\">)</span>：</span><font face=\"Calibri\"><span style=\"FONT-FAMILY: 仿宋_GB2312; COLOR: black; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt; mso-bidi-font-size: 16.0pt; mso-fareast-font-family: 宋体; mso-fareast-theme-font: minor-fareast; mso-hansi-font-family: 仿宋\" lang=\"EN-US\">1720000</span><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\" lang=\"EN-US\"><o:p></o:p></span></font></p>\n" +
                "<p style=\"TEXT-ALIGN: left; LINE-HEIGHT: 18pt; TEXT-INDENT: 18pt; MARGIN: 0cm 0cm 0pt; mso-char-indent-count: 1.5; mso-pagination: widow-orphan\" class=\"MsoNormal\" align=\"left\"><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\">第二名：经评审的投标报价<span lang=\"EN-US\">(</span>元<span lang=\"EN-US\">)</span>：</span><font face=\"Calibri\"><span style=\"FONT-FAMILY: 仿宋_GB2312; COLOR: black; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt; mso-bidi-font-size: 16.0pt; mso-fareast-font-family: 宋体; mso-fareast-theme-font: minor-fareast; mso-hansi-font-family: 仿宋\" lang=\"EN-US\">1780000</span><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\" lang=\"EN-US\"><o:p></o:p></span></font></p>\n" +
                "<p style=\"TEXT-ALIGN: left; LINE-HEIGHT: 18pt; TEXT-INDENT: 18pt; MARGIN: 0cm 0cm 0pt; mso-char-indent-count: 1.5; mso-pagination: widow-orphan\" class=\"MsoNormal\" align=\"left\"><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\">第三名：经评审的投标报价<span lang=\"EN-US\">(</span>元<span lang=\"EN-US\">)</span>：</span><font face=\"Calibri\"><span style=\"FONT-FAMILY: 仿宋_GB2312; COLOR: black; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt; mso-bidi-font-size: 16.0pt; mso-fareast-font-family: 宋体; mso-fareast-theme-font: minor-fareast; mso-hansi-font-family: 仿宋\" lang=\"EN-US\">1790000</span><u><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\" lang=\"EN-US\"><o:p></o:p></span></u></font></p>\n" +
                "<p style=\"TEXT-ALIGN: left; LINE-HEIGHT: 18pt; MARGIN: 0cm 0cm 0pt; mso-pagination: widow-orphan\" class=\"MsoNormal\" align=\"left\"><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\" lang=\"EN-US\"><o:p>&nbsp;</o:p></span></p>\n" +
                "<p style=\"TEXT-ALIGN: left; TEXT-INDENT: 28.45pt; MARGIN: 0cm 0cm 0pt; mso-char-indent-count: 2.36; mso-pagination: widow-orphan\" class=\"MsoNormal\" align=\"left\"><b style=\"mso-bidi-font-weight: normal\"><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\">二、中标候选人资格、质量、工期、负责人资质以及评标情况：<span lang=\"EN-US\"><o:p></o:p></span></span></b></p>\n" +
                "<p style=\"TEXT-ALIGN: left; TEXT-INDENT: 28.45pt; MARGIN: 0cm 0cm 0pt; mso-char-indent-count: 2.36; mso-pagination: widow-orphan\" class=\"MsoNormal\" align=\"left\"><b style=\"mso-bidi-font-weight: normal\"><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\" lang=\"EN-US\"><o:p>&nbsp;</o:p></span></b></p>\n" +
                "<p style=\"TEXT-ALIGN: left; TEXT-INDENT: 28.3pt; MARGIN: 0cm 0cm 0pt; mso-char-indent-count: 2.36; mso-pagination: widow-orphan\" class=\"MsoNormal\" align=\"left\"><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\">（</span><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 9pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\">标段号<span lang=\"EN-US\">/</span>包件号）<span lang=\"EN-US\">:(</span>标段<span lang=\"EN-US\">/</span>包件名称：勘察设计<span lang=\"EN-US\">)<b style=\"mso-bidi-font-weight: normal\"><o:p></o:p></b></span></span></p>\n" +
                "<table style=\"BORDER-BOTTOM: medium none; BORDER-LEFT: medium none; MARGIN: 2.75pt 6.75pt; BORDER-COLLAPSE: collapse; BORDER-TOP: medium none; BORDER-RIGHT: medium none; mso-table-layout-alt: fixed; mso-border-alt: solid windowtext .5pt; mso-yfti-tbllook: 1184; mso-table-lspace: 9.0pt; mso-table-rspace: 9.0pt; mso-table-tspace: 5.0pt; mso-table-bspace: 5.0pt; mso-table-anchor-vertical: paragraph; mso-table-anchor-horizontal: margin; mso-table-left: center; mso-table-top: 7.9pt; mso-padding-alt: 0cm 5.4pt 0cm 5.4pt\" class=\"MsoNormalTable\" border=\"1\" cellspacing=\"0\" cellpadding=\"0\" width=\"527\" align=\"left\">\n" +
                "<tbody>\n" +
                "<tr style=\"HEIGHT: 20.8pt; mso-yfti-irow: 0; mso-yfti-firstrow: yes\">\n" +
                "<td style=\"BORDER-BOTTOM: windowtext 1pt solid; BORDER-LEFT: windowtext 1pt solid; PADDING-BOTTOM: 0cm; BACKGROUND-COLOR: transparent; PADDING-LEFT: 5.4pt; WIDTH: 33.55pt; PADDING-RIGHT: 5.4pt; HEIGHT: 20.8pt; BORDER-TOP: windowtext 1pt solid; BORDER-RIGHT: windowtext 1pt solid; PADDING-TOP: 0cm; mso-border-alt: solid windowtext .5pt\" width=\"45\">\n" +
                "<p style=\"TEXT-ALIGN: center; MARGIN: 0cm 0cm 0pt; mso-pagination: widow-orphan; mso-margin-top-alt: auto; mso-margin-bottom-alt: auto; mso-outline-level: 1; mso-element: frame; mso-element-frame-hspace: 9.0pt; mso-element-frame-vspace: 5.0pt; mso-element-wrap: around; mso-element-anchor-vertical: paragraph; mso-element-anchor-horizontal: margin; mso-element-left: center; mso-element-top: 7.9pt; mso-height-rule: exactly\" class=\"MsoNormal\" align=\"center\"><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 9pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\">序号<span lang=\"EN-US\"><o:p></o:p></span></span></p></td>\n" +
                "<td style=\"BORDER-BOTTOM: windowtext 1pt solid; BORDER-LEFT: #f0f0f0; PADDING-BOTTOM: 0cm; BACKGROUND-COLOR: transparent; PADDING-LEFT: 5.4pt; WIDTH: 63.95pt; PADDING-RIGHT: 5.4pt; HEIGHT: 20.8pt; BORDER-TOP: windowtext 1pt solid; BORDER-RIGHT: windowtext 1pt solid; PADDING-TOP: 0cm; mso-border-alt: solid windowtext .5pt; mso-border-left-alt: solid windowtext .5pt\" width=\"85\">\n" +
                "<p style=\"TEXT-ALIGN: center; MARGIN: 0cm 0cm 0pt; mso-pagination: widow-orphan; mso-margin-top-alt: auto; mso-margin-bottom-alt: auto; mso-outline-level: 1; mso-element: frame; mso-element-frame-hspace: 9.0pt; mso-element-frame-vspace: 5.0pt; mso-element-wrap: around; mso-element-anchor-vertical: paragraph; mso-element-anchor-horizontal: margin; mso-element-left: center; mso-element-top: 7.9pt; mso-height-rule: exactly\" class=\"MsoNormal\" align=\"center\"><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 9pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\">推荐顺序<span lang=\"EN-US\"><o:p></o:p></span></span></p></td>\n" +
                "<td style=\"BORDER-BOTTOM: windowtext 1pt solid; BORDER-LEFT: #f0f0f0; PADDING-BOTTOM: 0cm; BACKGROUND-COLOR: transparent; PADDING-LEFT: 5.4pt; WIDTH: 85pt; PADDING-RIGHT: 5.4pt; HEIGHT: 20.8pt; BORDER-TOP: windowtext 1pt solid; BORDER-RIGHT: windowtext 1pt solid; PADDING-TOP: 0cm; mso-border-alt: solid windowtext .5pt; mso-border-left-alt: solid windowtext .5pt\" width=\"113\">\n" +
                "<p style=\"TEXT-ALIGN: center; MARGIN: 0cm 0cm 0pt; mso-pagination: widow-orphan; mso-margin-top-alt: auto; mso-margin-bottom-alt: auto; mso-outline-level: 1; mso-element: frame; mso-element-frame-hspace: 9.0pt; mso-element-frame-vspace: 5.0pt; mso-element-wrap: around; mso-element-anchor-vertical: paragraph; mso-element-anchor-horizontal: margin; mso-element-left: center; mso-element-top: 7.9pt; mso-height-rule: exactly\" class=\"MsoNormal\" align=\"center\"><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 9pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\">第一名<span lang=\"EN-US\"><o:p></o:p></span></span></p></td>\n" +
                "<td style=\"BORDER-BOTTOM: windowtext 1pt solid; BORDER-LEFT: #f0f0f0; PADDING-BOTTOM: 0cm; BACKGROUND-COLOR: transparent; PADDING-LEFT: 5.4pt; WIDTH: 127.7pt; PADDING-RIGHT: 5.4pt; HEIGHT: 20.8pt; BORDER-TOP: windowtext 1pt solid; BORDER-RIGHT: windowtext 1pt solid; PADDING-TOP: 0cm; mso-border-alt: solid windowtext .5pt; mso-border-left-alt: solid windowtext .5pt\" width=\"170\">\n" +
                "<p style=\"TEXT-ALIGN: center; MARGIN: 0cm 0cm 0pt; mso-pagination: widow-orphan; mso-margin-top-alt: auto; mso-margin-bottom-alt: auto; mso-outline-level: 1; mso-element: frame; mso-element-frame-hspace: 9.0pt; mso-element-frame-vspace: 5.0pt; mso-element-wrap: around; mso-element-anchor-vertical: paragraph; mso-element-anchor-horizontal: margin; mso-element-left: center; mso-element-top: 7.9pt; mso-height-rule: exactly\" class=\"MsoNormal\" align=\"center\"><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 9pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\">第二名<span lang=\"EN-US\"><o:p></o:p></span></span></p></td>\n" +
                "<td style=\"BORDER-BOTTOM: windowtext 1pt solid; BORDER-LEFT: #f0f0f0; PADDING-BOTTOM: 0cm; BACKGROUND-COLOR: transparent; PADDING-LEFT: 5.4pt; WIDTH: 3cm; PADDING-RIGHT: 5.4pt; HEIGHT: 20.8pt; BORDER-TOP: windowtext 1pt solid; BORDER-RIGHT: windowtext 1pt solid; PADDING-TOP: 0cm; mso-border-alt: solid windowtext .5pt; mso-border-left-alt: solid windowtext .5pt\" width=\"113\">\n" +
                "<p style=\"TEXT-ALIGN: center; MARGIN: 0cm 0cm 0pt; mso-pagination: widow-orphan; mso-margin-top-alt: auto; mso-margin-bottom-alt: auto; mso-outline-level: 1; mso-element: frame; mso-element-frame-hspace: 9.0pt; mso-element-frame-vspace: 5.0pt; mso-element-wrap: around; mso-element-anchor-vertical: paragraph; mso-element-anchor-horizontal: margin; mso-element-left: center; mso-element-top: 7.9pt; mso-height-rule: exactly\" class=\"MsoNormal\" align=\"center\"><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 9pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\">第三名<span lang=\"EN-US\"><o:p></o:p></span></span></p></td></tr>\n" +
                "<tr style=\"HEIGHT: 42.55pt; mso-yfti-irow: 1\">\n" +
                "<td style=\"BORDER-BOTTOM: windowtext 1pt solid; BORDER-LEFT: windowtext 1pt solid; PADDING-BOTTOM: 0cm; BACKGROUND-COLOR: transparent; PADDING-LEFT: 5.4pt; WIDTH: 33.55pt; PADDING-RIGHT: 5.4pt; HEIGHT: 42.55pt; BORDER-TOP: #f0f0f0; BORDER-RIGHT: windowtext 1pt solid; PADDING-TOP: 0cm; mso-border-alt: solid windowtext .5pt; mso-border-top-alt: solid windowtext .5pt\" width=\"45\">\n" +
                "<p style=\"TEXT-ALIGN: center; MARGIN: 0cm 0cm 0pt; mso-pagination: widow-orphan; mso-margin-top-alt: auto; mso-margin-bottom-alt: auto; mso-outline-level: 1; mso-element: frame; mso-element-frame-hspace: 9.0pt; mso-element-frame-vspace: 5.0pt; mso-element-wrap: around; mso-element-anchor-vertical: paragraph; mso-element-anchor-horizontal: margin; mso-element-left: center; mso-element-top: 7.9pt; mso-height-rule: exactly\" class=\"MsoNormal\" align=\"center\"><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 9pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\" lang=\"EN-US\">1<o:p></o:p></span></p></td>\n" +
                "<td style=\"BORDER-BOTTOM: windowtext 1pt solid; BORDER-LEFT: #f0f0f0; PADDING-BOTTOM: 0cm; BACKGROUND-COLOR: transparent; PADDING-LEFT: 5.4pt; WIDTH: 63.95pt; PADDING-RIGHT: 5.4pt; HEIGHT: 42.55pt; BORDER-TOP: #f0f0f0; BORDER-RIGHT: windowtext 1pt solid; PADDING-TOP: 0cm; mso-border-alt: solid windowtext .5pt; mso-border-left-alt: solid windowtext .5pt; mso-border-top-alt: solid windowtext .5pt\" width=\"85\">\n" +
                "<p style=\"TEXT-ALIGN: center; MARGIN: 0cm 0cm 0pt; mso-pagination: widow-orphan; mso-margin-top-alt: auto; mso-margin-bottom-alt: auto; mso-outline-level: 1; mso-element: frame; mso-element-frame-hspace: 9.0pt; mso-element-frame-vspace: 5.0pt; mso-element-wrap: around; mso-element-anchor-vertical: paragraph; mso-element-anchor-horizontal: margin; mso-element-left: center; mso-element-top: 7.9pt; mso-height-rule: exactly\" class=\"MsoNormal\" align=\"center\"><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 9pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\">中标候选人名称<span lang=\"EN-US\"><o:p></o:p></span></span></p></td>\n" +
                "<td style=\"BORDER-BOTTOM: windowtext 1pt solid; BORDER-LEFT: #f0f0f0; PADDING-BOTTOM: 0cm; BACKGROUND-COLOR: transparent; PADDING-LEFT: 5.4pt; WIDTH: 85pt; PADDING-RIGHT: 5.4pt; HEIGHT: 42.55pt; BORDER-TOP: #f0f0f0; BORDER-RIGHT: windowtext 1pt solid; PADDING-TOP: 0cm; mso-border-alt: solid windowtext .5pt; mso-border-left-alt: solid windowtext .5pt; mso-border-top-alt: solid windowtext .5pt\" width=\"113\">\n" +
                "<p style=\"TEXT-ALIGN: center; MARGIN: 0cm 0cm 0pt; mso-pagination: widow-orphan; mso-margin-top-alt: auto; mso-margin-bottom-alt: auto; mso-outline-level: 1; mso-element: frame; mso-element-frame-hspace: 9.0pt; mso-element-frame-vspace: 5.0pt; mso-element-wrap: around; mso-element-anchor-vertical: paragraph; mso-element-anchor-horizontal: margin; mso-element-left: center; mso-element-top: 7.9pt; mso-height-rule: exactly\" class=\"MsoNormal\" align=\"center\"><span style=\"FONT-FAMILY: 宋体; FONT-SIZE: 9pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt; mso-ascii-font-family: 仿宋_GB2312; mso-fareast-font-family: 宋体; mso-fareast-theme-font: minor-fareast; mso-hansi-font-family: 仿宋\">中铁第六勘察设计院集团有限公司</span><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 9pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\" lang=\"EN-US\"><o:p></o:p></span></p></td>\n" +
                "<td style=\"BORDER-BOTTOM: windowtext 1pt solid; BORDER-LEFT: #f0f0f0; PADDING-BOTTOM: 0cm; BACKGROUND-COLOR: transparent; PADDING-LEFT: 5.4pt; WIDTH: 127.7pt; PADDING-RIGHT: 5.4pt; HEIGHT: 42.55pt; BORDER-TOP: #f0f0f0; BORDER-RIGHT: windowtext 1pt solid; PADDING-TOP: 0cm; mso-border-alt: solid windowtext .5pt; mso-border-left-alt: solid windowtext .5pt; mso-border-top-alt: solid windowtext .5pt\" width=\"170\">\n" +
                "<p style=\"TEXT-ALIGN: center; MARGIN: 0cm 0cm 0pt; mso-pagination: widow-orphan; mso-margin-top-alt: auto; mso-margin-bottom-alt: auto; mso-outline-level: 1; mso-element: frame; mso-element-frame-hspace: 9.0pt; mso-element-frame-vspace: 5.0pt; mso-element-wrap: around; mso-element-anchor-vertical: paragraph; mso-element-anchor-horizontal: margin; mso-element-left: center; mso-element-top: 7.9pt; mso-height-rule: exactly\" class=\"MsoNormal\" align=\"center\"><span style=\"FONT-FAMILY: 宋体; FONT-SIZE: 9pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt; mso-ascii-font-family: 仿宋_GB2312; mso-fareast-font-family: 宋体; mso-fareast-theme-font: minor-fareast; mso-hansi-font-family: 仿宋\">北京全路通信信号研究设计院集团有限公司与山西省第十地质工程勘察院联合体</span><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 9pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\" lang=\"EN-US\"><o:p></o:p></span></p></td>\n" +
                "<td style=\"BORDER-BOTTOM: windowtext 1pt solid; BORDER-LEFT: #f0f0f0; PADDING-BOTTOM: 0cm; BACKGROUND-COLOR: transparent; PADDING-LEFT: 5.4pt; WIDTH: 3cm; PADDING-RIGHT: 5.4pt; HEIGHT: 42.55pt; BORDER-TOP: #f0f0f0; BORDER-RIGHT: windowtext 1pt solid; PADDING-TOP: 0cm; mso-border-alt: solid windowtext .5pt; mso-border-left-alt: solid windowtext .5pt; mso-border-top-alt: solid windowtext .5pt\" width=\"113\">\n" +
                "<p style=\"TEXT-ALIGN: center; MARGIN: 0cm 0cm 0pt; mso-pagination: widow-orphan; mso-margin-top-alt: auto; mso-margin-bottom-alt: auto; mso-outline-level: 1; mso-element: frame; mso-element-frame-hspace: 9.0pt; mso-element-frame-vspace: 5.0pt; mso-element-wrap: around; mso-element-anchor-vertical: paragraph; mso-element-anchor-horizontal: margin; mso-element-left: center; mso-element-top: 7.9pt; mso-height-rule: exactly\" class=\"MsoNormal\" align=\"center\"><span style=\"FONT-FAMILY: 宋体; FONT-SIZE: 9pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt; mso-ascii-font-family: 仿宋_GB2312; mso-fareast-font-family: 宋体; mso-fareast-theme-font: minor-fareast; mso-hansi-font-family: 仿宋\">中铁六局集团有限公司</span><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 9pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\" lang=\"EN-US\"><o:p></o:p></span></p></td></tr>\n" +
                "<tr style=\"HEIGHT: 5.05pt; mso-yfti-irow: 2\">\n" +
                "<td style=\"BORDER-BOTTOM: windowtext 1pt solid; BORDER-LEFT: windowtext 1pt solid; PADDING-BOTTOM: 0cm; BACKGROUND-COLOR: transparent; PADDING-LEFT: 5.4pt; WIDTH: 33.55pt; PADDING-RIGHT: 5.4pt; HEIGHT: 5.05pt; BORDER-TOP: #f0f0f0; BORDER-RIGHT: windowtext 1pt solid; PADDING-TOP: 0cm; mso-border-alt: solid windowtext .5pt; mso-border-top-alt: solid windowtext .5pt\" width=\"45\">\n" +
                "<p style=\"TEXT-ALIGN: center; MARGIN: 0cm 0cm 0pt; mso-pagination: widow-orphan; mso-margin-top-alt: auto; mso-margin-bottom-alt: auto; mso-outline-level: 1; mso-element: frame; mso-element-frame-hspace: 9.0pt; mso-element-frame-vspace: 5.0pt; mso-element-wrap: around; mso-element-anchor-vertical: paragraph; mso-element-anchor-horizontal: margin; mso-element-left: center; mso-element-top: 7.9pt; mso-height-rule: exactly\" class=\"MsoNormal\" align=\"center\"><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 9pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\" lang=\"EN-US\">2<o:p></o:p></span></p></td>\n" +
                "<td style=\"BORDER-BOTTOM: windowtext 1pt solid; BORDER-LEFT: #f0f0f0; PADDING-BOTTOM: 0cm; BACKGROUND-COLOR: transparent; PADDING-LEFT: 5.4pt; WIDTH: 63.95pt; PADDING-RIGHT: 5.4pt; HEIGHT: 5.05pt; BORDER-TOP: #f0f0f0; BORDER-RIGHT: windowtext 1pt solid; PADDING-TOP: 0cm; mso-border-alt: solid windowtext .5pt; mso-border-left-alt: solid windowtext .5pt; mso-border-top-alt: solid windowtext .5pt\" width=\"85\">\n" +
                "<p style=\"TEXT-ALIGN: center; MARGIN: 0cm 0cm 0pt; mso-pagination: widow-orphan; mso-margin-top-alt: auto; mso-margin-bottom-alt: auto; mso-outline-level: 1; mso-element: frame; mso-element-frame-hspace: 9.0pt; mso-element-frame-vspace: 5.0pt; mso-element-wrap: around; mso-element-anchor-vertical: paragraph; mso-element-anchor-horizontal: margin; mso-element-left: center; mso-element-top: 7.9pt; mso-height-rule: exactly\" class=\"MsoNormal\" align=\"center\"><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 9pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\">质量<span lang=\"EN-US\"><o:p></o:p></span></span></p></td>\n" +
                "<td style=\"BORDER-BOTTOM: windowtext 1pt solid; BORDER-LEFT: #f0f0f0; PADDING-BOTTOM: 0cm; BACKGROUND-COLOR: transparent; PADDING-LEFT: 5.4pt; WIDTH: 85pt; PADDING-RIGHT: 5.4pt; HEIGHT: 5.05pt; BORDER-TOP: #f0f0f0; BORDER-RIGHT: windowtext 1pt solid; PADDING-TOP: 0cm; mso-border-alt: solid windowtext .5pt; mso-border-left-alt: solid windowtext .5pt; mso-border-top-alt: solid windowtext .5pt\" width=\"113\">\n" +
                "<p style=\"TEXT-ALIGN: center; MARGIN: 0cm 0cm 0pt; mso-pagination: widow-orphan; mso-margin-top-alt: auto; mso-margin-bottom-alt: auto; mso-outline-level: 1; mso-element: frame; mso-element-frame-hspace: 9.0pt; mso-element-frame-vspace: 5.0pt; mso-element-wrap: around; mso-element-anchor-vertical: paragraph; mso-element-anchor-horizontal: margin; mso-element-left: center; mso-element-top: 7.9pt; mso-height-rule: exactly\" class=\"MsoNormal\" align=\"center\"><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 9pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\">合格<span lang=\"EN-US\"><o:p></o:p></span></span></p></td>\n" +
                "<td style=\"BORDER-BOTTOM: windowtext 1pt solid; BORDER-LEFT: #f0f0f0; PADDING-BOTTOM: 0cm; BACKGROUND-COLOR: transparent; PADDING-LEFT: 5.4pt; WIDTH: 127.7pt; PADDING-RIGHT: 5.4pt; HEIGHT: 5.05pt; BORDER-TOP: #f0f0f0; BORDER-RIGHT: windowtext 1pt solid; PADDING-TOP: 0cm; mso-border-alt: solid windowtext .5pt; mso-border-left-alt: solid windowtext .5pt; mso-border-top-alt: solid windowtext .5pt\" width=\"170\">\n" +
                "<p style=\"TEXT-ALIGN: center; MARGIN: 0cm 0cm 0pt; mso-pagination: widow-orphan; mso-margin-top-alt: auto; mso-margin-bottom-alt: auto; mso-outline-level: 1; mso-element: frame; mso-element-frame-hspace: 9.0pt; mso-element-frame-vspace: 5.0pt; mso-element-wrap: around; mso-element-anchor-vertical: paragraph; mso-element-anchor-horizontal: margin; mso-element-left: center; mso-element-top: 7.9pt; mso-height-rule: exactly\" class=\"MsoNormal\" align=\"center\"><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 9pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\">合格<span lang=\"EN-US\"><o:p></o:p></span></span></p></td>\n" +
                "<td style=\"BORDER-BOTTOM: windowtext 1pt solid; BORDER-LEFT: #f0f0f0; PADDING-BOTTOM: 0cm; BACKGROUND-COLOR: transparent; PADDING-LEFT: 5.4pt; WIDTH: 3cm; PADDING-RIGHT: 5.4pt; HEIGHT: 5.05pt; BORDER-TOP: #f0f0f0; BORDER-RIGHT: windowtext 1pt solid; PADDING-TOP: 0cm; mso-border-alt: solid windowtext .5pt; mso-border-left-alt: solid windowtext .5pt; mso-border-top-alt: solid windowtext .5pt\" width=\"113\">\n" +
                "<p style=\"TEXT-ALIGN: center; MARGIN: 0cm 0cm 0pt; mso-pagination: widow-orphan; mso-margin-top-alt: auto; mso-margin-bottom-alt: auto; mso-outline-level: 1; mso-element: frame; mso-element-frame-hspace: 9.0pt; mso-element-frame-vspace: 5.0pt; mso-element-wrap: around; mso-element-anchor-vertical: paragraph; mso-element-anchor-horizontal: margin; mso-element-left: center; mso-element-top: 7.9pt; mso-height-rule: exactly\" class=\"MsoNormal\" align=\"center\"><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 9pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\">合格<span lang=\"EN-US\"><o:p></o:p></span></span></p></td></tr>\n" +
                "<tr style=\"HEIGHT: 2.4pt; mso-yfti-irow: 3; mso-yfti-lastrow: yes\">\n" +
                "<td style=\"BORDER-BOTTOM: windowtext 1pt solid; BORDER-LEFT: windowtext 1pt solid; PADDING-BOTTOM: 0cm; BACKGROUND-COLOR: transparent; PADDING-LEFT: 5.4pt; WIDTH: 33.55pt; PADDING-RIGHT: 5.4pt; HEIGHT: 2.4pt; BORDER-TOP: #f0f0f0; BORDER-RIGHT: windowtext 1pt solid; PADDING-TOP: 0cm; mso-border-alt: solid windowtext .5pt; mso-border-top-alt: solid windowtext .5pt\" width=\"45\">\n" +
                "<p style=\"TEXT-ALIGN: center; MARGIN: 0cm 0cm 0pt; mso-pagination: widow-orphan; mso-margin-top-alt: auto; mso-margin-bottom-alt: auto; mso-outline-level: 1; mso-element: frame; mso-element-frame-hspace: 9.0pt; mso-element-frame-vspace: 5.0pt; mso-element-wrap: around; mso-element-anchor-vertical: paragraph; mso-element-anchor-horizontal: margin; mso-element-left: center; mso-element-top: 7.9pt; mso-height-rule: exactly\" class=\"MsoNormal\" align=\"center\"><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 9pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\" lang=\"EN-US\">3<o:p></o:p></span></p></td>\n" +
                "<td style=\"BORDER-BOTTOM: windowtext 1pt solid; BORDER-LEFT: #f0f0f0; PADDING-BOTTOM: 0cm; BACKGROUND-COLOR: transparent; PADDING-LEFT: 5.4pt; WIDTH: 63.95pt; PADDING-RIGHT: 5.4pt; HEIGHT: 2.4pt; BORDER-TOP: #f0f0f0; BORDER-RIGHT: windowtext 1pt solid; PADDING-TOP: 0cm; mso-border-alt: solid windowtext .5pt; mso-border-left-alt: solid windowtext .5pt; mso-border-top-alt: solid windowtext .5pt\" width=\"85\">\n" +
                "<p style=\"TEXT-ALIGN: center; MARGIN: 0cm 0cm 0pt; mso-pagination: widow-orphan; mso-margin-top-alt: auto; mso-margin-bottom-alt: auto; mso-outline-level: 1; mso-element: frame; mso-element-frame-hspace: 9.0pt; mso-element-frame-vspace: 5.0pt; mso-element-wrap: around; mso-element-anchor-vertical: paragraph; mso-element-anchor-horizontal: margin; mso-element-left: center; mso-element-top: 7.9pt; mso-height-rule: exactly\" class=\"MsoNormal\" align=\"center\"><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 9pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\">工期<span lang=\"EN-US\"><o:p></o:p></span></span></p></td>\n" +
                "<td style=\"BORDER-BOTTOM: windowtext 1pt solid; BORDER-LEFT: #f0f0f0; PADDING-BOTTOM: 0cm; BACKGROUND-COLOR: transparent; PADDING-LEFT: 5.4pt; WIDTH: 85pt; PADDING-RIGHT: 5.4pt; HEIGHT: 2.4pt; BORDER-TOP: #f0f0f0; BORDER-RIGHT: windowtext 1pt solid; PADDING-TOP: 0cm; mso-border-alt: solid windowtext .5pt; mso-border-left-alt: solid windowtext .5pt; mso-border-top-alt: solid windowtext .5pt\" width=\"113\">\n" +
                "<p style=\"TEXT-ALIGN: center; MARGIN: 0cm 0cm 0pt; mso-pagination: widow-orphan; mso-margin-top-alt: auto; mso-margin-bottom-alt: auto; mso-outline-level: 1; mso-element: frame; mso-element-frame-hspace: 9.0pt; mso-element-frame-vspace: 5.0pt; mso-element-wrap: around; mso-element-anchor-vertical: paragraph; mso-element-anchor-horizontal: margin; mso-element-left: center; mso-element-top: 7.9pt; mso-height-rule: exactly\" class=\"MsoNormal\" align=\"center\"><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 9pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\" lang=\"EN-US\">2</span><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 9pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\">个月<span lang=\"EN-US\"><o:p></o:p></span></span></p></td>\n" +
                "<td style=\"BORDER-BOTTOM: windowtext 1pt solid; BORDER-LEFT: #f0f0f0; PADDING-BOTTOM: 0cm; BACKGROUND-COLOR: transparent; PADDING-LEFT: 5.4pt; WIDTH: 127.7pt; PADDING-RIGHT: 5.4pt; HEIGHT: 2.4pt; BORDER-TOP: #f0f0f0; BORDER-RIGHT: windowtext 1pt solid; PADDING-TOP: 0cm; mso-border-alt: solid windowtext .5pt; mso-border-left-alt: solid windowtext .5pt; mso-border-top-alt: solid windowtext .5pt\" width=\"170\">\n" +
                "<p style=\"TEXT-ALIGN: center; MARGIN: 0cm 0cm 0pt; mso-pagination: widow-orphan; mso-margin-top-alt: auto; mso-margin-bottom-alt: auto; mso-outline-level: 1; mso-element: frame; mso-element-frame-hspace: 9.0pt; mso-element-frame-vspace: 5.0pt; mso-element-wrap: around; mso-element-anchor-vertical: paragraph; mso-element-anchor-horizontal: margin; mso-element-left: center; mso-element-top: 7.9pt; mso-height-rule: exactly\" class=\"MsoNormal\" align=\"center\"><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 9pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\" lang=\"EN-US\">2</span><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 9pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\">个月<span lang=\"EN-US\"><o:p></o:p></span></span></p></td>\n" +
                "<td style=\"BORDER-BOTTOM: windowtext 1pt solid; BORDER-LEFT: #f0f0f0; PADDING-BOTTOM: 0cm; BACKGROUND-COLOR: transparent; PADDING-LEFT: 5.4pt; WIDTH: 3cm; PADDING-RIGHT: 5.4pt; HEIGHT: 2.4pt; BORDER-TOP: #f0f0f0; BORDER-RIGHT: windowtext 1pt solid; PADDING-TOP: 0cm; mso-border-alt: solid windowtext .5pt; mso-border-left-alt: solid windowtext .5pt; mso-border-top-alt: solid windowtext .5pt\" width=\"113\">\n" +
                "<p style=\"TEXT-ALIGN: center; MARGIN: 0cm 0cm 0pt; mso-pagination: widow-orphan; mso-element: frame; mso-element-frame-hspace: 9.0pt; mso-element-frame-vspace: 5.0pt; mso-element-wrap: around; mso-element-anchor-vertical: paragraph; mso-element-anchor-horizontal: margin; mso-element-left: center; mso-element-top: 7.9pt; mso-height-rule: exactly\" class=\"MsoNormal\" align=\"center\"><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 9pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\" lang=\"EN-US\">2</span><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 9pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\">个月<span lang=\"EN-US\"><o:p></o:p></span></span></p></td></tr></tbody></table>\n" +
                "<p style=\"TEXT-ALIGN: left; MARGIN: 0cm 0cm 0pt; mso-pagination: widow-orphan\" class=\"MsoNormal\" align=\"left\"><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\"></span>&nbsp;</p>\n" +
                "<p style=\"TEXT-ALIGN: left; MARGIN: 0cm 0cm 0pt; mso-pagination: widow-orphan\" class=\"MsoNormal\" align=\"left\"><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\"></span>&nbsp;</p>\n" +
                "<p style=\"TEXT-ALIGN: left; MARGIN: 0cm 0cm 0pt; mso-pagination: widow-orphan\" class=\"MsoNormal\" align=\"left\"><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\"></span>&nbsp;</p>\n" +
                "<p style=\"TEXT-ALIGN: left; MARGIN: 0cm 0cm 0pt; mso-pagination: widow-orphan\" class=\"MsoNormal\" align=\"left\"><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\"></span>&nbsp;</p>\n" +
                "<p style=\"TEXT-ALIGN: left; MARGIN: 0cm 0cm 0pt; mso-pagination: widow-orphan\" class=\"MsoNormal\" align=\"left\"><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\"></span>&nbsp;</p>\n" +
                "<p style=\"TEXT-ALIGN: left; MARGIN: 0cm 0cm 0pt; mso-pagination: widow-orphan\" class=\"MsoNormal\" align=\"left\"><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\"></span>&nbsp;</p>\n" +
                "<p style=\"TEXT-ALIGN: left; MARGIN: 0cm 0cm 0pt; mso-pagination: widow-orphan\" class=\"MsoNormal\" align=\"left\"><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\"></span>&nbsp;</p>\n" +
                "<p style=\"TEXT-ALIGN: left; MARGIN: 0cm 0cm 0pt; mso-pagination: widow-orphan\" class=\"MsoNormal\" align=\"left\"><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\">第一名<span lang=\"EN-US\">;</span>项目负责人姓名<span lang=\"EN-US\">:</span>吴书伟<span lang=\"EN-US\">;</span>职业资格<span lang=\"EN-US\">:</span>高级工程师<span lang=\"EN-US\">;</span>证书编号<span lang=\"EN-US\">:</span></span><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 9pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\" lang=\"EN-US\"> </span><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\" lang=\"EN-US\">3408013090<o:p></o:p></span></p>\n" +
                "<p style=\"TEXT-ALIGN: left; MARGIN: 0cm 0cm 0pt; mso-pagination: widow-orphan; tab-stops: 41.25pt\" class=\"MsoNormal\" align=\"left\"><span style=\"FONT-FAMILY: 宋体; COLOR: black; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt; mso-ascii-font-family: 'Times New Roman'; mso-fareast-font-family: 宋体; mso-fareast-theme-font: minor-fareast; mso-hansi-font-family: 'Times New Roman'; mso-bidi-font-weight: bold\">业绩</span><span style=\"FONT-FAMILY: 'Times New Roman','serif'; COLOR: black; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt; mso-bidi-font-weight: bold\" lang=\"EN-US\">:</span><span style=\"FONT-FAMILY: 宋体; COLOR: black; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt; mso-ascii-font-family: 'Times New Roman'; mso-fareast-font-family: 宋体; mso-fareast-theme-font: minor-fareast; mso-hansi-font-family: 'Times New Roman'; mso-bidi-font-weight: bold\">京通铁路朝阳地址通辽段电气化改造工程等</span><span style=\"FONT-FAMILY: 'Times New Roman','serif'; COLOR: black; FONT-SIZE: 12pt; mso-bidi-font-family: 'Times New Roman'; mso-font-kerning: 0pt; mso-fareast-font-family: 宋体; mso-bidi-theme-font: minor-bidi; mso-bidi-font-weight: bold\" lang=\"EN-US\">6</span><span style=\"FONT-FAMILY: 宋体; COLOR: black; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt; mso-ascii-font-family: 'Times New Roman'; mso-fareast-font-family: 宋体; mso-fareast-theme-font: minor-fareast; mso-hansi-font-family: 'Times New Roman'; mso-bidi-font-weight: bold\">项工程。</span><span style=\"FONT-FAMILY: 'Times New Roman','serif'; COLOR: black; FONT-SIZE: 12pt; mso-bidi-font-family: 'Times New Roman'; mso-font-kerning: 0pt; mso-fareast-font-family: 宋体; mso-bidi-theme-font: minor-bidi; mso-bidi-font-weight: bold\" lang=\"EN-US\"><o:p></o:p></span></p>\n" +
                "<p style=\"TEXT-ALIGN: left; MARGIN: 0cm 0cm 0pt; mso-pagination: widow-orphan\" class=\"MsoNormal\" align=\"left\"><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\">投标人业绩<span lang=\"EN-US\">:<o:p></o:p></span></span></p>\n" +
                "<p style=\"TEXT-ALIGN: left; MARGIN: 0cm 0cm 0pt; mso-pagination: widow-orphan\" class=\"MsoNormal\" align=\"left\"><span style=\"FONT-FAMILY: 宋体; COLOR: black; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt; mso-bidi-font-size: 10.5pt; mso-fareast-font-family: 宋体; mso-fareast-theme-font: minor-fareast\">芜湖至广德铁路电气化改造工程铁路建设工程及</span><span style=\"FONT-FAMILY: 宋体; COLOR: black; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt; mso-bidi-font-size: 10.5pt; mso-ascii-font-family: Calibri; mso-ascii-theme-font: minor-latin; mso-fareast-font-family: 宋体; mso-fareast-theme-font: minor-fareast; mso-hansi-font-family: Calibri; mso-hansi-theme-font: minor-latin\">京通铁路朝阳地至通辽段电气化改造工程等</span><span style=\"COLOR: black; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt; mso-bidi-font-size: 10.5pt; mso-ascii-font-family: Calibri; mso-fareast-font-family: 宋体; mso-hansi-font-family: Calibri\" lang=\"EN-US\"><font face=\"Calibri\">5</font></span><span style=\"FONT-FAMILY: 宋体; COLOR: black; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt; mso-bidi-font-size: 10.5pt; mso-ascii-font-family: Calibri; mso-ascii-theme-font: minor-latin; mso-fareast-font-family: 宋体; mso-fareast-theme-font: minor-fareast; mso-hansi-font-family: Calibri; mso-hansi-theme-font: minor-latin\">项</span><span style=\"FONT-FAMILY: 宋体; COLOR: black; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt; mso-bidi-font-size: 10.5pt; mso-fareast-font-family: 宋体; mso-fareast-theme-font: minor-fareast\">勘察设计</span><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\" lang=\"EN-US\"><o:p></o:p></span></p>\n" +
                "<p style=\"TEXT-ALIGN: left; MARGIN: 0cm 0cm 0pt; mso-pagination: widow-orphan\" class=\"MsoNormal\" align=\"left\"><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\">第二名<span lang=\"EN-US\">; </span>项目负责人姓名<span lang=\"EN-US\">:</span>李雪<span lang=\"EN-US\">;</span>职业资格<span lang=\"EN-US\">:</span>高级工程师<span lang=\"EN-US\">;</span>证书编号<span lang=\"EN-US\">:</span></span><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 9pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\" lang=\"EN-US\"> </span><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\" lang=\"EN-US\">8901000699<o:p></o:p></span></p>\n" +
                "<p style=\"TEXT-ALIGN: left; MARGIN: 0cm 0cm 0pt; mso-pagination: widow-orphan\" class=\"MsoNormal\" align=\"left\"><span style=\"FONT-FAMILY: 宋体; COLOR: black; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt; mso-bidi-font-size: 10.5pt; mso-fareast-font-family: 宋体; mso-fareast-theme-font: minor-fareast\">业绩<span lang=\"EN-US\">:</span>沈阳铁路局<span lang=\"EN-US\">GSM-R</span>网络建设工程（沈山线、沟海线）等<span lang=\"EN-US\">3</span>项工程。<span lang=\"EN-US\"><o:p></o:p></span></span></p>\n" +
                "<p style=\"TEXT-ALIGN: left; MARGIN: 0cm 0cm 0pt; mso-pagination: widow-orphan\" class=\"MsoNormal\" align=\"left\"><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\">投标人业绩<span lang=\"EN-US\">:<o:p></o:p></span></span></p>\n" +
                "<p style=\"TEXT-ALIGN: left; MARGIN: 0cm 0cm 0pt; mso-pagination: widow-orphan\" class=\"MsoNormal\" align=\"left\"><span style=\"FONT-FAMILY: 宋体; COLOR: black; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt; mso-bidi-font-size: 10.5pt; mso-fareast-font-family: 宋体; mso-fareast-theme-font: minor-fareast\">石太线局管内<span lang=\"EN-US\">G</span>网建设工程及沈山裕国至锦州段数字移动通信系统（<span lang=\"EN-US\">GSM-R</span>）建设工程等<span lang=\"EN-US\">4</span>项勘察设计。<span lang=\"EN-US\"><o:p></o:p></span></span></p>\n" +
                "<p style=\"TEXT-ALIGN: left; MARGIN: 0cm 0cm 0pt; mso-pagination: widow-orphan\" class=\"MsoNormal\" align=\"left\"><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\">第三名<span lang=\"EN-US\">; </span>项目负责人姓名<span lang=\"EN-US\">:</span>毕晋峰<span lang=\"EN-US\">;</span>职业资格<span lang=\"EN-US\">:</span>高级工程师<span lang=\"EN-US\">;</span>证书编号<span lang=\"EN-US\">:</span></span><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 9pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\" lang=\"EN-US\"> </span><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\" lang=\"EN-US\">340611072001082<o:p></o:p></span></p>\n" +
                "<p style=\"TEXT-ALIGN: left; MARGIN: 0cm 0cm 0pt; mso-pagination: widow-orphan\" class=\"MsoNormal\" align=\"left\"><span style=\"FONT-FAMILY: 宋体; COLOR: black; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt; mso-bidi-font-size: 10.5pt; mso-fareast-font-family: 宋体; mso-fareast-theme-font: minor-fareast\">业绩</span><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\" lang=\"EN-US\">:</span><span style=\"FONT-FAMILY: 宋体; COLOR: black; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt; mso-bidi-font-size: 10.5pt; mso-fareast-font-family: 宋体; mso-fareast-theme-font: minor-fareast\">北京局生产力布局调整运输站段联网及开通视频会议系统工程等<span lang=\"EN-US\">3</span>项工程。<span lang=\"EN-US\"><o:p></o:p></span></span></p>\n" +
                "<p style=\"TEXT-ALIGN: left; MARGIN: 0cm 0cm 0pt; mso-pagination: widow-orphan\" class=\"MsoNormal\" align=\"left\"><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\">投标人业绩<span lang=\"EN-US\">:<o:p></o:p></span></span></p>\n" +
                "<p style=\"TEXT-ALIGN: left; MARGIN: 0cm 0cm 0pt; mso-pagination: widow-orphan\" class=\"MsoNormal\" align=\"left\"><span style=\"FONT-FAMILY: 宋体; COLOR: black; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt; mso-bidi-font-size: 10.5pt; mso-fareast-font-family: 宋体; mso-fareast-theme-font: minor-fareast\">北京地下至线站改造过度工程设计及北京局生产力布局调整运输站段联网及开通视频会议系统工程设计。<span lang=\"EN-US\"><o:p></o:p></span></span></p>\n" +
                "<p style=\"TEXT-ALIGN: left; MARGIN: 0cm 0cm 0pt; mso-pagination: widow-orphan\" class=\"MsoNormal\" align=\"left\"><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\">评标情况：上述三家投标人均符合招标文件要求，全部通过评审。<span lang=\"EN-US\"><o:p></o:p></span></span></p>\n" +
                "<p style=\"TEXT-ALIGN: left; TEXT-INDENT: 29.5pt; MARGIN: 0cm 0cm 0pt; mso-char-indent-count: 2.45; mso-pagination: widow-orphan; mso-margin-top-alt: auto; mso-margin-bottom-alt: auto; mso-outline-level: 1\" class=\"MsoNormal\" align=\"left\"><b style=\"mso-bidi-font-weight: normal\"><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\">三、公示日期：自<span lang=\"EN-US\">2018</span>年<span lang=\"EN-US\">4</span>月<span lang=\"EN-US\">8</span>日至<span lang=\"EN-US\">2018</span>年<span lang=\"EN-US\">4</span>月<span lang=\"EN-US\">10</span>日止。<span lang=\"EN-US\"><o:p></o:p></span></span></b></p>\n" +
                "<p style=\"TEXT-ALIGN: left; TEXT-INDENT: 28.3pt; MARGIN: 0cm 0cm 0pt; mso-char-indent-count: 2.36; mso-pagination: widow-orphan; mso-margin-top-alt: auto; mso-margin-bottom-alt: auto; mso-outline-level: 1\" class=\"MsoNormal\" align=\"left\"><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\">在公示期间，所有投标人和其他利害关系人对评标结果有异议的，根据《招标投标活动投诉处理办法》（七部委<span lang=\"EN-US\">2004</span>年<span lang=\"EN-US\">11</span>号令）、《中华人民共和国招标投标法实施条例》和《招标公告和招标公示信息发布管理办法》（发展改革委<span lang=\"EN-US\">2017</span>年<span lang=\"EN-US\">10</span>号令）向招标人书面提出。<span lang=\"EN-US\"><o:p></o:p></span></span></p>\n" +
                "<p style=\"TEXT-ALIGN: left; LINE-HEIGHT: 12pt; TEXT-INDENT: 28.45pt; MARGIN: 0cm 0cm 0pt; mso-char-indent-count: 2.36; mso-pagination: widow-orphan; mso-line-height-rule: exactly\" class=\"MsoNormal\" align=\"left\"><b style=\"mso-bidi-font-weight: normal\"><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\">四、联系方式：<span lang=\"EN-US\"><o:p></o:p></span></span></b></p>\n" +
                "<p style=\"TEXT-ALIGN: left; LINE-HEIGHT: 12pt; TEXT-INDENT: 28.3pt; MARGIN: 0cm 0cm 0pt; mso-char-indent-count: 2.36; mso-pagination: widow-orphan; mso-margin-top-alt: auto; mso-margin-bottom-alt: auto; mso-outline-level: 1; mso-line-height-rule: exactly\" class=\"MsoNormal\" align=\"left\"><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\" lang=\"EN-US\">1.</span><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\">招标人<span lang=\"EN-US\">: </span>中国铁路沈阳局集团有限公司辽西工程建设指挥部<span lang=\"EN-US\"><o:p></o:p></span></span></p>\n" +
                "<p style=\"TEXT-ALIGN: left; LINE-HEIGHT: 12pt; TEXT-INDENT: 28.3pt; MARGIN: 0cm 0cm 0pt; mso-char-indent-count: 2.36; mso-pagination: widow-orphan; mso-margin-top-alt: auto; mso-margin-bottom-alt: auto; mso-outline-level: 1; mso-line-height-rule: exactly\" class=\"MsoNormal\" align=\"left\"><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\">地址：辽宁省锦州市凌河区和平路五段<span lang=\"EN-US\">4</span>号<span lang=\"EN-US\"><o:p></o:p></span></span></p>\n" +
                "<p style=\"TEXT-ALIGN: left; LINE-HEIGHT: 12pt; TEXT-INDENT: 28.3pt; MARGIN: 0cm 0cm 0pt; mso-char-indent-count: 2.36; mso-pagination: widow-orphan; mso-margin-top-alt: auto; mso-margin-bottom-alt: auto; mso-outline-level: 1; mso-line-height-rule: exactly\" class=\"MsoNormal\" align=\"left\"><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\">联系人<span lang=\"EN-US\">:</span>纪光辉<span lang=\"EN-US\"><o:p></o:p></span></span></p>\n" +
                "<p style=\"TEXT-ALIGN: left; LINE-HEIGHT: 12pt; TEXT-INDENT: 28.3pt; MARGIN: 0cm 0cm 0pt; mso-char-indent-count: 2.36; mso-pagination: widow-orphan; mso-margin-top-alt: auto; mso-margin-bottom-alt: auto; mso-outline-level: 1; mso-line-height-rule: exactly\" class=\"MsoNormal\" align=\"left\"><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\">联系电话<span lang=\"EN-US\">:0416-2553527<o:p></o:p></span></span></p>\n" +
                "<p style=\"TEXT-ALIGN: left; LINE-HEIGHT: 12pt; TEXT-INDENT: 30pt; MARGIN: 0cm 0cm 0pt; mso-char-indent-count: 2.5; mso-pagination: widow-orphan; mso-line-height-rule: exactly\" class=\"MsoNormal\" align=\"left\"><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\">传真<span lang=\"EN-US\">/</span>邮箱：<span lang=\"EN-US\">0416-2553527/ lxzhbjgh@163.com<o:p></o:p></span></span></p>\n" +
                "<p style=\"TEXT-ALIGN: left; LINE-HEIGHT: 12pt; TEXT-INDENT: 30pt; MARGIN: 0cm 0cm 0pt; mso-char-indent-count: 2.5; mso-pagination: widow-orphan; mso-margin-top-alt: auto; mso-margin-bottom-alt: auto; mso-outline-level: 1; mso-line-height-rule: exactly\" class=\"MsoNormal\" align=\"left\"><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\" lang=\"EN-US\">2</span><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\">．行业主管部门：中国铁路沈阳局集团有限公司建设工程招投标管理办公室<span lang=\"EN-US\"><o:p></o:p></span></span></p>\n" +
                "<p style=\"TEXT-ALIGN: left; LINE-HEIGHT: 12pt; TEXT-INDENT: 30pt; MARGIN: 0cm 0cm 0pt; mso-char-indent-count: 2.5; mso-pagination: widow-orphan; mso-line-height-rule: exactly\" class=\"MsoNormal\" align=\"left\"><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\">地址：沈阳市和平区太原北街<span lang=\"EN-US\">4</span>号<span lang=\"EN-US\"><o:p></o:p></span></span></p>\n" +
                "<p style=\"TEXT-ALIGN: left; LINE-HEIGHT: 12pt; TEXT-INDENT: 28.3pt; MARGIN: 0cm 0cm 0pt; mso-char-indent-count: 2.36; mso-pagination: widow-orphan; mso-margin-top-alt: auto; mso-margin-bottom-alt: auto; mso-outline-level: 1; mso-line-height-rule: exactly\" class=\"MsoNormal\" align=\"left\"><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\">联系人<span lang=\"EN-US\">:</span>孙伟东<span lang=\"EN-US\"><o:p></o:p></span></span></p>\n" +
                "<p style=\"TEXT-ALIGN: left; LINE-HEIGHT: 12pt; TEXT-INDENT: 28.3pt; MARGIN: 0cm 0cm 0pt; mso-char-indent-count: 2.36; mso-pagination: widow-orphan; mso-margin-top-alt: auto; mso-margin-bottom-alt: auto; mso-outline-level: 1; mso-line-height-rule: exactly\" class=\"MsoNormal\" align=\"left\"><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\">联系电话<span lang=\"EN-US\">:024-62028347<o:p></o:p></span></span></p>\n" +
                "<p style=\"TEXT-ALIGN: left; LINE-HEIGHT: 12pt; TEXT-INDENT: 28.3pt; MARGIN: 0cm 0cm 0pt; mso-char-indent-count: 2.36; mso-pagination: widow-orphan; mso-margin-top-alt: auto; mso-margin-bottom-alt: auto; mso-outline-level: 1; mso-line-height-rule: exactly\" class=\"MsoNormal\" align=\"left\"><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\">传真<span lang=\"EN-US\">/</span>邮箱：<span lang=\"EN-US\">024-62028367<o:p></o:p></span></span></p>\n" +
                "<p style=\"TEXT-ALIGN: left; LINE-HEIGHT: 12pt; MARGIN: 0cm 0cm 0pt; mso-pagination: widow-orphan; mso-line-height-rule: exactly\" class=\"MsoNormal\" align=\"left\"><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt\" lang=\"EN-US\"><o:p>&nbsp;</o:p></span></p><span style=\"FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt; mso-ansi-language: EN-US; mso-fareast-language: ZH-CN; mso-bidi-language: AR-SA\">日期：<span lang=\"EN-US\">2018</span>年<span lang=\"EN-US\">4</span>月<span lang=\"EN-US\">8</span>日</span> </td>";
        noticeTableAnalysis.analysis(null,s3);
    }

    @Test
    public void testUtils(){
        String s ="中标候选人名称";
        String regex="(中标人|中标单位|中标候选人|候选人|投标人|投标单位)";
        System.out.println("####"+RegexUtils.matchExists(s,regex));
    }

    @Test
    public void testOthers(){
//        String s="            ";
//        System.out.println(MyStringUtils.isNotNull(s));
//        System.out.println(s.replaceAll("[  ]","").length());
        String[] vs = new String[]{"1","2","3"};
        vs = Arrays.copyOfRange(vs,1,vs.length);
        System.out.println(Arrays.deepToString(vs));
    }


}
